### ISSUE TITLE
Are you going to release your training codes this week?

### ISSUE THREAD

**Issue by xinrui-zhuang** [hqqxyy/msspl#1]
Great job！

**Comment by hqqxyy** [comment]
Thank you for your interest.  I am not sure whether I can release the training codes this week. Our dataset is still reviewed by Intel to double-check the licenses. Our training codes are closely related to our dataset. It contains a lot of tricks to speed up the loading time of exr data. We cannot train the model without the dataset. Thus we planned to release the codes and dataset together. I will let you know when the code is released. Thanks.
